# LanceDB vector database

In [12]:
import lancedb

db = lancedb.connect(uri="vector_database")
db

LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database')

In [13]:
db.uri

'c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'

## Read in data

In [14]:
import json

with open("data/animals_text_embeddings.json", "r") as file:
    data = json.loads(file.read())

data

[{'text': 'A small brown dog running.', 'vector': [0.12, 0.85, 0.33]},
 {'text': 'A cat resting quietly on a sofa.', 'vector': [0.4, 0.91, 0.1]},
 {'text': 'A large gray elephant drinking water.',
  'vector': [0.88, 0.22, 0.55]},
 {'text': 'A fast cheetah sprinting across the savannah.',
  'vector': [0.95, 0.12, 0.72]},
 {'text': 'A colorful parrot perched on a branch.',
  'vector': [0.25, 0.66, 0.81]},
 {'text': 'A frog sitting on a lily pad.', 'vector': [0.14, 0.44, 0.27]}]

In [15]:
db.create_table("animals", exist_ok=True, data=data)

LanceTable(name='animals', version=1, _conn=LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'))

In [16]:
db.list_tables()

ListTablesResponse(tables=['animals'], page_token=None)

In [17]:
db["animals"]

LanceTable(name='animals', version=1, _conn=LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'))

In [18]:
db["animals"].head()

pyarrow.Table
text: string
vector: fixed_size_list<item: float>[3]
  child 0, item: float
----
text: [["A small brown dog running.","A cat resting quietly on a sofa.","A large gray elephant drinking water.","A fast cheetah sprinting across the savannah.","A colorful parrot perched on a branch."]]
vector: [[[0.12,0.85,0.33],[0.4,0.91,0.1],[0.88,0.22,0.55],[0.95,0.12,0.72],[0.25,0.66,0.81]]]

In [21]:
df_animals = db["animals"].to_pandas()
df_animals

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]

In [20]:
df_animals.iloc

NameError: name 'df_animals' is not defined

## To add more data

In [22]:
more_data = [
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
]

db["animals"].add(more_data)

AddResult(version=2)

In [23]:
db["animals"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

## Create empty table
- Create an empty table first, then place in data
- Need to provide schema

In [ ]:
from lancedb.pydantic import LanceModel

class EmployeeSchema(LanceModel):
    first_name: str
    last_name: str
    salary: int

db.create_table(name = "employees",schema=EmployeeSchema, exist_ok=True)

LanceTable(name='employees', version=1, _conn=LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'))

In [30]:
data = [{"first_name": "Bibbi", "last_name": "Babblarna", "salary": 1000}]
db["employees"].add(data)

AddResult(version=2)

In [32]:
db["employees"].to_pandas()

  first_name  last_name  salary
0      Bibbi  Babblarna    1000

In [33]:
db.list_tables()

ListTablesResponse(tables=['animals', 'employees'], page_token=None)

In [34]:
db.drop_table("employees")

In [35]:
db.list_tables()

ListTablesResponse(tables=['animals'], page_token=None)